### ISSUE TITLE
Can you tell me if the mobile API signing server or web?

### ISSUE THREAD

**Issue by prairieson** [aithedevv/X-Gorgon#1]
Can you tell me if the mobile API signing server or web? Here too https://github.com/merlinssh/TikTok-Library describes the signature server, how different are you?

**Comment by aithedevv** [comment]
bro what

**Comment by prairieson** [comment]
Do you have an encryption algorithm for device_register (ttencrypt)?

**Comment by aithedevv** [comment]
yes i have ttencrypt, just message my telegram
